from datetime import datetime

from langchain.agents import create_agent

from stock_analyst.interpretations import CalculationInterpretation
from stock_analyst.report_download_models import DownloadedReport
from stock_analyst.llm_provider import DEFAULT_MODEL, get_model_name
from stock_analyst.quantitative_data import RawQuantitativeData
from stock_analyst.stock_directory import StockInfo

author_agent = create_agent(
    model=DEFAULT_MODEL,
    system_prompt="You are a financial analyst. You have been given information about "
    "a company's financial performance report. Your job is to summarize the report "
    "in a way that is easy to understand for a non-financial person.",
)


async def write_report(
    stock_info: StockInfo,
    downloaded_filing: DownloadedReport,
    unusual_values: list[CalculationInterpretation],
    commentary: list[str],
    parsed_values: RawQuantitativeData,
) -> str:
    return f"""
---
# {stock_info.name} ({stock_info.ticker})
#### {datetime.now().strftime("%Y-%m-%d")}
#### Model: {get_model_name()}
#### Report: {downloaded_filing.file_path.name}

*Disclaimer: This report was generated by an AI agent, which is still under development.*
*It is still prone to errors and omissions. All numbers should be verified by independent sources.*

*This is not financial advice. Do your own due diligence before investing.*

---

## Summary
{await summarize_unusual_values(unusual_values)}

{await summarize_commentary(commentary)}

---

## Unusual Values
{write_unusual_values_as_markdown(unusual_values)}

---

## Commentary
{to_markdown_list(commentary)}

---

## Raw Values
{parsed_values}

"""

async def summarize_unusual_values(
    unusual_values: list[CalculationInterpretation],
) -> str:
    message = f"""
I ran a fundamental analysis calculations on the company's financial performance report.

Here are the unusual values found in the calculations:
{write_unusual_values_as_markdown(unusual_values)}

Please summarize the unusual values concisely in one paragraph.
Add a few sentences of commentary at the end about the company's valuation and future performance
"""
    result = await author_agent.ainvoke({"messages": [{"role": "user", "content": message}]})
    return result["messages"][-1].text


async def summarize_commentary(
    commentary: list[str],
) -> str:
    message = f"""
I ran a fundamental analysis calculations on the company's financial performance report.

Here are some interesting insights from the report:
{to_markdown_list(commentary)}

Please summarize the insights concisely in one paragraph.
Make sure to highlight any insights that could have a significant impact
on the company's valuation and future performance.
"""
    result = await author_agent.ainvoke({"messages": [{"role": "user", "content": message}]})
    return result["messages"][-1].text


def to_markdown_list(items: list[str]) -> str:
    return "\n".join([f"- {item}" for item in items])

def write_unusual_values_as_markdown(unusual_values: list[CalculationInterpretation]) -> str:
    output = ""
    for value in unusual_values:
        output += f"**{value.field_name}**: {value.raw_value:.2f}\n({value.interpretation})\n\n"
    return output
